### ISSUE TITLE
link Leaflet js API to app

### ISSUE THREAD

**Issue by nicolepeak** [ALLHUBS-Jan-2024-Liftoff/The-Coding-Sharks#24]
Complete the basic API link to the front-end UI

**Comment by nicolepeak** [comment]
I created the component that will house the main map functionality. It includes placeholder locations that we will eventually grab from our database. I then integrated it into the App.jsx to test the render.

**Comment by shellywilliamsreichert802** [comment]
Way to get started!!! Looks great a few things to consider...
-Might need to add a key prop to each Marker since React requires a unique key prop for each array element to help identify changes, added or removed items
-Add Popup to each Marker to display popUp text when marker is clicked
Alternate code suggestion:
          {markers.map((marker, index) => (
            <Marker key={index} position={marker.geocode}>
              <Popup>{marker.popUp}</Popup>
            </Marker>
          ))}

**Comment by shellywilliamsreichert802** [comment]
{markers.map((marker, index) => (
            <Marker key={index} position={marker.geocode}>
              <Popup>{marker.popUp}</Popup>
            </Marker>
          ))}
